project:
  title: "qtm350-summer-quiz02"
  type: website

output-dir: docs

website:
  navbar:
    right:
      - text: "Home Page"
        href: index.qmd
      - text: "Life Expectancy and GDP per Capita"
        href: life-gdp.qmd
      - text: "Life Expectancy and Population"
        href: life-population.qmd
      - text: "Country Analysis"
        href: country.qmd

format:
  html:
    theme: cerulean